name: Validate

on:
  push:           # run on every push to any branch
  pull_request:
  workflow_dispatch:
  schedule:
  - cron:  '0 0 * * *'

jobs:
  validate-hacs:
    name: HACS Validation
    runs-on: ubuntu-latest
    steps:
      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "integration"

  validate-hassfest:
    name: Hassfest Validation
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v3"
      - uses: home-assistant/actions/hassfest@master

  lint:
    name: Lint with Ruff
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Lint with ruff
        run: |
          ruff check custom_components/tineco
